### ISSUE TITLE
Detect MEDICAL_LICENSE

### ISSUE THREAD

**Issue by zjpittman** [NCATComp410/comp410_fall_2024#12]
**Description** 

Every medical specialist has to obtain a medical license to legally practice. 

**Detection Steps** 

There are many different patterns for medical license numbers. Using regular expressions to pattern match the most common medical lisence numbers will be the best course of action. In North Carolina the medical license numbers contain 5-6 numbers and no letters. Those are examples of patterns I will check for.

**Comment by claesmk** [comment]
@zjpittman do you have any references to what sort of checksum you might want to implement?

**Comment by zjpittman** [comment]
> @zjpittman do you have any references to what sort of checksum you might want to implement?

This was actually a typo. Thanks for reminding me. I was going to do checksum and soon realized that would be too complex for this type of project.

**Comment by siblount** [comment]
@troylion What are your thoughts on this?

**Comment by troylion** [comment]
Looks good! Very clear description. The use of regular expressions for detecting medical license numbers looks good. Just wondering if different variations in patterns across different states would be accounted for?
