### ISSUE TITLE
Detect IN_PAN

### ISSUE THREAD

**Issue by doudoumdh** [NCATComp410/comp410_fall_2024#13]
### Description
Permanent Account Number (PAN) is a unique number issued by Income Tax Department of India. PAN is also issued to Non-Resident Indians (NRI), Person of Indian Origin (PIO), Overseas Citizen of India (OCI), & Foreign Companies. A IN_PAN is an important PII type because it is used to file taxes and it contains personal identification information of the owner. To learn more about IN_PAN number, visit [here](https://en.wikipedia.org/wiki/Permanent_account_number)

### Detection Steps
The IN_PAN  is a ten-character long alpha-numeric unique identifier. 
Example: **AAAPZ1234C**

**Comment by Jolisa-dot** [comment]
Why does the PAN have to be a mix of numbers and letters?

**Comment by doudoumdh** [comment]
> Why does the PAN have to be a mix of numbers and letters?

The letters are not chosen at random, in fact, Wikipedia has a breakdown of the sequence. I'll just paste it;

The first five characters are letters (in uppercase by default), followed by four numerals, and the last (tenth) character is a letter.
The first three characters of the code are three letters forming a sequence of alphabetical letters from AAA to ZZZ
The fourth character identifies the type of holder of the card. Each holder type is uniquely defined by a letter from the list below:
A — AOP (Association of persons)
B — BOI (Body of individuals)
C — Company
F — Firm
G — Government
H — HUF (Hindu Undivided Family)
L — Local authority
J — Artificial juridical person
P — Person (Individual)
T — Trust (AOP)
The fifth character of the PAN is the first character of either of the first name, surname or last name of the person
The last (tenth) character is an alphabetic digit used as a check-sum to verify the validity of that current code.

**Comment by claesmk** [comment]
Looks good
