### ISSUE TITLE
Detect IN_AADHAAR

### ISSUE THREAD

**Issue by Jolisa-dot** [NCATComp410/comp410_fall_2024#14]
### Description
AADHAAR is an Indian government-issued unique 12-digit individual identity number. It serves as proof of identity and address in India. It is free to enroll in and was created to eliminate fake and duplicate identities in government databases. To find more information click [here](https://www.uidai.gov.in/en/16-english-uk/aapka-aadhaar/14-what-is-aadhaar.html#:~:text=Aadhaar%20is%20a%2012%20digit%20individual%20identification%20number%20issued%20by,and%20address%2C%20anywhere%20in%20India.).

### Detection Steps
- Each individual will be given a single unique Aadhaar ID number
- Aadhaar will provide a universal identity infrastructure that can be used by any identity-based application 
- UIDAI will give Yes/No answers to any identity authentication queries
- AADHAAR also uses based face authentication to improve privacy [here](https://github.com/NCATComp410/comp410_fall_2024/issues/14)

**Comment by doudoumdh** [comment]
Hey @Jolisa-dot, would you consider the AADHAAR equivalent to US_SSN or Id Number?

**Comment by Jolisa-dot** [comment]
> Hey @Jolisa-dot, would you consider the AADHAAR equivalent to US_SSN or Id Number?

The AADHAAR is more equivalent to the US_SSN. They are both unique identifiers used for administrative,legal, and financial purposes.

**Comment by Pojohnson-XJ** [comment]
How accurate is the based face authentication?

**Comment by AbdoulZeba** [comment]
> How accurate is the based face authentication?

It’s very accurate and reliable way to authenticate users. It can identify as long as they are registered the AADHAAR

**Comment by claesmk** [comment]
@Jolisa-dot it would be good if your detection steps included that you are looking for a 12-digit number and any context words that would help to strengthen the identification
