### ISSUE TITLE
Detect IN_VEHICLE_REGISTRATION

### ISSUE THREAD

**Issue by Dyamondgrate** [NCATComp410/comp410_fall_2024#15]
Description:
This issue pertains to the registration number assigned to vehicles in India that are issued by the government. It includes all categories such as government vehicles, personal vehicles owned by government officials, diplomatic vehicles, and those used by the defense sector. The vehicle registration number serves as an official identifier in compliance with Indian transport regulations on license plates.

Detection Steps:

- Color of the Plate:
Private vehicle: Black Lettering on white background
Commercial Vehicles: Black Lettering on yellow background
Rental Vehicles: Yellow Lettering on black background
Foreign Embassy or Consulate: White Lettering on light blue background
Electric Vehicles: White Lettering on green background
Indian President or Governor: State emblem of India in Gold on red background

- Numbers on the plates:

First two character: Denotes the Federal State or Union Territory
Next two: Indicates the regional transport authority within the state or territory
Next one or two letters: Shows the current series of Registration numbers
Final Four Digits: Numbers unique to the plate

**Comment by claesmk** [comment]
@Dyamondgrate who will this be assigned to and what are the detection steps?

**Comment by lailacodes** [comment]
Hey @Dyamondgrate, what's the format of the IN_VEHICLE_REGISTRATION? Is it similar to say a license plate number on vehicles?

**Comment by Dyamondgrate** [comment]
Hey @lailacodes Yes, The vehicle registration is the actually whats on the license plate. I've updated my issue to further answer your question.

**Comment by danabrunson** [comment]
Hey @Dyamondgrate, what dictates the first 3 characters being letters compared to 4?
