### ISSUE TITLE
IP_ADDRESS:  Internet Protocol (IP) address (either IPv4 or IPv6).

### ISSUE THREAD

**Issue by Pojohnson-XJ** [NCATComp410/comp410_fall_2024#17]
### Description
When you surf the web and go online you have something called a IP Address, this allows you to differentiate while on the internet. You need this to search the web or scroll online to learn more about it [here](https://www.fortinet.com/resources/cyberglossary/what-is-ip-address#:~:text=What%20is%20the%20use%20of,%2Darea%20networks%20(LANs).)

  - Why is it important? 
    In the world we live in today almost everything can be done online, such as shopping, checking your bank account or even paying bills. So if a hacker were to come in and do something like a man-in-the-middle attack, they could get access to your sensitive information. Then they could possibility pretend to be you and steal money or sell your information to others.
     
### Detection Steps
For detecting an IPv4 address

  - all ips are start with 3 numbers followed by a period such as 216.27.61.137
  - they use 32 binary bits to create a single unique address

to learn more click either of this link [one ](https://computer.howstuffworks.com/internet/basics/what-is-an-ip-address.htm)

**Comment by Jmnobles1** [comment]
what could make someone more susceptible to having there IP Address leaked or having there network attacked?

**Comment by ComicalTNM** [comment]
How do detect if something is an IP address or not? Is there a format for IP addresses?

**Comment by claesmk** [comment]
@Pojohnson-XJ your detection steps are not relevant for this assignment.  You are looking for text based representation of an IP address - for example - 192.168.1.10 should be detected as an IP address. 

An IPv6 address can pose a more serious risk than IPv4 addresses.  Can you discuss why that is?
