### ISSUE TITLE
Detect IN_PASSPORT

### ISSUE THREAD

**Issue by lailacodes** [NCATComp410/comp410_fall_2024#18]
**DESCRIPTION**

An IN_PASSPORT (Indian Passport Number) is a unique number assigned by the Government of India to passport holders. It certifies the identity and citizenship of the passport holder for international travel. It is important to detect IN_PASSPORT to prevent potential identity theft and fraud, and to ensure the passport holder's sensitive information remains secure and protected. 

**DETECTION STEPS**

An IN_PASSPORT consists of eight characters:
- The first character **must be an uppercase letter** (A-Z)
- The remaining seven characters are a combination of **integers** (0-9) 

_Example: E7654321_

**Comment by Dyamondgrate** [comment]
Hey @lailacodes, Question, should the detection process reject passport numbers that contain any alphanumeric character or lower case letter ?

**Comment by lailacodes** [comment]
@Dyamondgrate Lowercase letters are not used in the IN_PASSPORT, so it should reject them. The IN_PASSPORT number should also adhere to the format of the first character being an uppercase letter and the following characters being integers from 0-9. Also, I'm going to update the detection steps for more clarity because none of the characters should be symbols either.

**Comment by claesmk** [comment]
Looks good

**Comment by Lmill5** [comment]
Is there a specific regular expression we should use to detect the IN_PASSPORT format accurately?

**Comment by AbdoulZeba** [comment]
Seems very interesting how an individuals personal information is protected
