### ISSUE TITLE
Detect IT_DRIVER_LICENSE

### ISSUE THREAD

**Issue by mawdogbe** [NCATComp410/comp410_fall_2024#19]
Description:
Italian driver's licenses are based on a [European standard ](https://en.wikipedia.org/wiki/European_driving_licence)for driver's licenses. These licenses have a 10-digit alphanumeric license number that can be used to identify a license holder. It is important to protect these license numbers as they can be used for identity fraud.

Detection Steps:
- one letter (not case-sensitive)
- the letter "A" or "V" (not case-sensitive)
- seven digits
- one letter (not case-sensitive)

Example: _AS5196744P_

**Comment by claesmk** [comment]
Looks good

**Comment by NCATAGGIES** [comment]
If I had the example of the number you gave >> AS5196744P >> how can I know the holder of the license?

**Comment by mawdogbe** [comment]
Similar to SSNs, this number could be used within a database to find a potential target. It's more of a way in than a solid identifier, if that makes sense.
