### ISSUE TITLE
Add detection for CREDIT_CARD PII type

### ISSUE THREAD

**Issue by siblount** [NCATComp410/comp410_fall_2024#2]
### Description
Credit cards is a common form of payment used for our everyday lives. In most cases, it can be as a data point to identify a specific individual. We don't want this type of data accidentally on the web for anyone to see. A huge privacy nightmare. Let's scan for the CREDIT_CARD PII type.

Microsoft Presidio has support for the CREDIT_CARD PII type seen [here](https://microsoft.github.io/presidio/supported_entities/).
### Detection steps

1) A credit card number is between 12-18 digits
2) We can use that to detect finding a string within 12-18 digits consecutively without whitespaces. 
3) A credit card starts with a 6-8 digit IIN
4) After the 6-8 digit IIN number, the rest are individual account identification numbers, excluding the last digit.
5) The last digit is a Luhn check digit for verification for the Luhn's algorithm.
6) We can use Luhn's algorithm to detect if a number is valid or not. However, only most card numbers will be detected as a very few cannot be verified with Luhn's algorithm.
7) Because of this, we will simply use Microsoft Presidio library to detect CREDIT_CARD types, the code will look something like this:

```py
from presidio_analyzer import AnalyzerEngine
from presidio_anonymizer import AnonymizerEngine

text="My super secret credit card number 6011 0030 8111 9999"

# Set up the engine, loads the NLP module (spaCy model by default) 
# and other PII recognizers
analyzer = AnalyzerEngine()

# Call analyzer to get results
results = analyzer.analyze(text=text,
                           entities=["CREDIT_CARD"],
                           language='en')
print(results)
```

**Comment by skybot00** [comment]
Nice! it's honestly very detailed and even has a code example.

**Comment by siblount** [comment]
Thanks!

**Comment by claesmk** [comment]
Looks good - you might find [this](https://developer.squareup.com/docs/devtools/sandbox/payments) page helpful for some test credit card numbers.  Do you think you will detect an AMEX number OK?

**Comment by siblount** [comment]
Thanks for the resource @claesmk! I'll take a look into it.

By AMEX, I am assuming you mean American Express, if so, then yes. According to the [wikipedia](https://en.wikipedia.org/wiki/Payment_card_number), American Express can be verified using the [Luhn algorithm](https://en.wikipedia.org/wiki/Luhn_algorithm).

With my plan of using Microsoft Presidio, although it doesn't explicitly state AMEX numbers are supported. I did find this [gem](https://learn.microsoft.com/en-us/purview/sit-defn-credit-card-number#pattern':~:text=Detects%20cards%20from%20all%20major%20brands%2C%20including%20Visa%2C%20MasterCard%2C%20Discover%20Card%2C%20JCB%2C%20American%20Express%2C) where it mentions:

> Detects cards from all major brands, including Visa, MasterCard, Discover Card, JCB, **American Express**, ...

Of course, we will test this theory out.

**Comment by Camfrm336** [comment]
Sounds good! I appreciate the code example along with the detailed methodology.
