### ISSUE TITLE
Detect FI_PERSONAL_IDENTITY_CODE 

### ISSUE THREAD

**Issue by JaylenParks50** [NCATComp410/comp410_fall_2024#20]
The FI_PERSONAL_IDENTITY_CODE or Finnish Personal Identity Code is a unique 11 character individual identity number. It is a permanent unique personal identifier that no two people share in Finland. Banks, insurance companies, and private health care providers may all use this code to verify identities for whom they issue services. These codes are issued to anyone who is registered in Finland’s Population Information System. For more information please look [here](https://dvv.fi/en/personal-identity-code).

Protection of this specific PII is very important because it is a unique personal identifier, only one person has each code and if someone else has your code they can misuse it for unsavory things like identity fraud. This is one of the few circumstances where an individual can apply to change their code.

Detection:
This PII can be detected by its format of DDMMYYCZZZQ where DDMMYY is the day, month, and year of birth, C is the century marker, ZZZ is the individual number between 002-899 which is odd if male and even if female, and Q is the control character. Q is determined by taking the DDMMYYZZZ number dividing it by 31 or mod 31 and using that remainder to pick from the following string, “0123456789ABCDEFHJKLMNPRSTUVWXY.” More information on detecting it can be found [here](https://cran.r-project.org/web/packages/hetu/vignettes/hetu.html).

**Comment by Jason-Nobles** [comment]
What exactly does the century marker indicate, and is it an optional character in the Personal Identity code?

**Comment by claesmk** [comment]
@JaylenParks50 Looks good - agree century marker could be clarified more

**Comment by ZachLCOMP** [comment]
> What exactly does the century marker indicate, and is it an optional character in the Personal Identity code?

The century marker indicates the century that individual was born in. It is a plus sign (+) for individuals born in the 19th century, a hyphen (-) or letter Y for individuals born in the 20th century, and the letter A for those born in the 21st century. It is not optional.
