### ISSUE TITLE
Detect IT_PASSPORT

### ISSUE THREAD

**Issue by everett-alanHood** [NCATComp410/comp410_fall_2024#21]
### Description
AN IT_PASSPORT (Italian Passport) includes a distinct nine-character string assigned by the the Italian Citizenship Assistance (ICA). There are two types of IT_PASSPORTs: ordinary and temporary. It is important to detect IT_PASSPORT in order to prevent personal information from being leaked and to prevent identity fraud and theft. For more information, click [here](https://italiancitizenshipassistance.com/the-italian-passport/).
### Detection Steps
An IT_PASSPORT consists of two digits or letters (not case-sensitive) followed by seven digits with no spaces or delimiters.

Example: JF3349917

**Comment by claesmk** [comment]
Looks good
