### ISSUE TITLE
Detect IN_VOTER

### ISSUE THREAD

**Issue by danabrunson** [NCATComp410/comp410_fall_2024#22]
### Description
Each Indian citizen is issued a unique voter ID by the Indian Election Commission once they reach 18 years of age. It serves as identity proof for citizens casting their ballot in municipal, state, and national elections.

### Detection Steps 
Each ID is 10 characters, consisting of 3 letters followed by 7 digits.

**Comment by Djgrandison944** [comment]
Are the three letters case-sensitive?

**Comment by claesmk** [comment]
Looks OK other than the comment about case-sensitive please clarify that.

**Comment by danabrunson** [comment]
> Are the three letters case-sensitive?

Yes. The letters must be capitalized.
