### ISSUE TITLE
Detect IT_IDENTITY_CARD

### ISSUE THREAD

**Issue by ComicalTNM** [NCATComp410/comp410_fall_2024#23]
### Description
The Italian electronic identity card is an identification document issued to any Italian citizen and to legal aliens. The CIE is intended for both digital and physical identification. The biometric information is printed on an ID-1 card and stored in a contactless chip. For more information click [here](https://en.wikipedia.org/wiki/Italian_electronic_identity_card).

### Detection Steps
The microprocessor chip in the identity card contains the name, surname, place and date of birth, residency, holder's picture, and two fingerprints (one of each hand, only if the applicant is aged 12 or over) of the individual. 

Example: Jane Doe, New York, New York, New York Apartments Building 5.

**Comment by Wbpatterson** [comment]
At what age would a citizen receive a CIE and does it need to be updated as the citizen ages?

**Comment by claesmk** [comment]
@ComicalTNM you won't have access to the chip - please focus on the text-based detection steps listed in the Presidio documentation (Pattern match and context)

**Comment by Lmill5** [comment]
For detection, it’s important to focus on the biometric data and the personal information stored in the card’s microchip, including the holder’s name, birth details, residency, and fingerprints for individuals aged 12 or over. Ensuring this data is protected and detected properly is critical for safeguarding identity.

**Comment by ComicalTNM** [comment]
Alright I will use the text-based detection method
