### ISSUE TITLE
Detect DATE_TIME

### ISSUE THREAD

**Issue by Camfrm336** [NCATComp410/comp410_fall_2024#3]
**Description**
A Date/Time is a type of PII that can reveal significant personal details such as birth dates, activity timestamps, or historical records.

**Detection Steps**
A Date/Time typically follows formats like YYYY-MM-DD, DD-MM-YYYY, MM-DD-YYYY, or timestamps such as YYYY-MM-DD HH:MM:SS, and can include variations based on locale or format settings.

**Comment by siblount** [comment]
Looks good to me!

**Comment by claesmk** [comment]
Looks good - nice that you included the MM-DD-YYYY format which gets used outside the US quite often

**Comment by zjpittman** [comment]
I think you would fall into issues with dates such as 8/5/2024 because there are no zeros before 8 and 5. times would have a similar issue as well. The pattern match technique would have to take into account those things as well.

**Comment by ChanningBarnes** [comment]
Looks good, I'm curious if this should also account for a date spelled out, such as 'September 11th,  2024.' Not sure how often you'd run into it though, seems like you have the most common use cases covered.
