### ISSUE TITLE
Detect EMAIL_ADDRESS

### ISSUE THREAD

**Issue by skybot00** [NCATComp410/comp410_fall_2024#4]
Description:
An email address is a type of PII that can directly reveal personal details such as identity, contact information, or even location of the individual. 

Detection Steps:
An Email Address basically follows the standard format of having a username (which could include letters, numbers, and special characters). Then the @ symbol which separates the username and domain. Lastly would be the domain, which also contains letters, numbers and special characters followed by .com, .org, and the list goes on.

**Comment by siblount** [comment]
The email does not have to end in .com, .org, or .etc. For example, my new email address I am migrating to is:
siblount@pm.me. I believe your assertion will fail.

Another example is:
siblount@aggies.ncat.edu
do-not-reply@sf2tj238t2905205252-252ghm@githubusercontent.eu

**Comment by skybot00** [comment]
yes, that is why i put etc after listing some examples, like the list goes on but i did not want to put all of them if that make sense. it was a grammar error on my part.

**Comment by claesmk** [comment]
This is a little more complicated as there is an RFC that defines valid email addresses, including characters and length.  Wikipedia has a good [write-up](https://en.wikipedia.org/wiki/Email_address) on it
