### ISSUE TITLE
Detect AU_ACN

### ISSUE THREAD

**Issue by AmariBull** [NCATComp410/comp410_fall_2024#5]
### Description
An AU_ACN is short for Australian Company Number, this is a unique nine-digit number given to every company registered under the Commonwealth Corporations Act 2001. This is an identifier issued by the Australian Securities and Invesments Commission.

This is a crucial form of PII which must be highly protected. For more information regarding the identity please see [here](https://microsoft.github.io/presidio/supported_entities/).

### Detection Steps
An AU_ACN consists of nine digits, where the first digit is any number from 1 to 9, and the following eight digits can range from 0 to 9. The final digit, known as the check digit, is calculated using a mathematical formula designed to ensure the validity of the number.

**Comment by fw1012** [comment]
What are the risk if AU_ACN is compromised?

**Comment by AmariBull** [comment]
> What are the risk if AU_ACN is compromised?

An ACN, similarly to an US Employer Identification Number, holds key information that if compromised could result in many issues. These issues include identity theft/fraud, liability issues, compromised security, and business relationship consequences. All of these could cost a company millions in damages so ensuring that everything is protected is of utmost importance.

**Comment by claesmk** [comment]
Looks good we'll get into how to differentiate this from other 9 digit numbers in the next sprint
