### ISSUE TITLE
Detect ABA_ROUTING_NUMBER

### ISSUE THREAD

**Issue by naomirross** [NCATComp410/comp410_fall_2024#6]
### Description
The ABA_ROUTING_NUMBER is a nine-digit code used to identify U.S banks for checks, direct deposits and transfers. It is considered personally identifiable information because it is linked to bank accounts which is sensitive information that should be protected. For more information see [here](https://www.aba.com/news-research/analysis-guides/routing-number-policy-procedures).
### Detection Steps
ABA_ROUTING_NUMBER is a nine-digit code. The first two digits indicate Federal Reserve district or regional processing center and range from 00 - 12, 21 to 32, or 61 to 72. The last digit is a checksum where the first, fourth and seventh digits are multiplied by three. The second, fifth and eighth digits are multiplied by seven. The third and sixth digits are multiplied by one. The total is summed and the ninth digit is the number that makes the total divisible by 10.

**Comment by AmariBull** [comment]
Does the routing number have the ability to be accessed universally outside of the primary country?

**Comment by naomirross** [comment]
> Does the routing number have the ability to be accessed universally outside of the primary country?

No, an ABA routing number is primarily used within the United States  and cannot be directly used for international transactions. International transfers tend to use other systems like SWIFT codes or IBANs.

**Comment by ToriJ25** [comment]
How could an individual find out if their routing number is stolen?

**Comment by claesmk** [comment]
Description and detection steps look good

**Comment by anrichardson1** [comment]
What security measures are used by banks to protect routing numbers?

**Comment by naomirross** [comment]
> How could an individual find out if their routing number is stolen?

One might run a credit report, check their bank statements,  or use other third-party fraud detection services. In the case that someone's routing number has been stolen a report can be filed with the Federal Trade Commission (FTC) https://www.identitytheft.gov/.

**Comment by naomirross** [comment]
> What security measures are used by banks to protect routing numbers?

Banks have a few methods including data encryption, multi-factor authentication and transaction limits.

**Comment by brycebenson54** [comment]
What are some examples of response plans that banks and credit unions have if a routing number were to get leaked as well as the accounting number?
