### ISSUE TITLE
Detect AU_MEDICARE

### ISSUE THREAD

**Issue by fw1012** [NCATComp410/comp410_fall_2024#7]
### Description
 An AU_MEDICARE is assigned by the Australian government to a cardholder. The cardholder will then receive medical notes/expenses under Australia's Medicare system. It is important to detect and protect AU_MEDICARE so fraudulent activity doesn't occur as well as ensuring private personal information is secure and won't be leaked. 

For more information, please click [here](https://microsoft.github.io/presidio/supported_entities/) to read about the PII.

### Detection Steps
The PII AU_MEDICARE can be detected by a pattern match, context and checksum. It is located above the name on the card. It can be verified by systems like Medicare Australia or Third-Party Services. The AU_MEDICARE is a card number that is 10 digits and  made up of the following parts:
* Card number: 7 digits
* Check digit: 1 digit
* Issue number: 1 digit
* Person number: 1 digit

Read more [here](https://www.usi.gov.au/students/identification/medicare-card#:~:text=Your%20Medicare%20Card%20must%20be,be%20selected%20from%20the%20list.).
Click [here](https://clearwater.com.au/code/medicare/) to see the validation code.

**Comment by naomirross** [comment]
How does the Australian government assign an AU_MEDICARE number?

**Comment by ToriJ25** [comment]
> How does the Australian government assign an AU_MEDICARE number?

Great question Naomi. Australian citizens, permanent residents, and some temporary residents with specific visas have to apply through the Medicare program and then assigned a medicare number and a card.

**Comment by claesmk** [comment]
Looks good - nice research on the details

**Comment by fw1012** [comment]
> Looks good - nice research on the details

Thank you!

**Comment by ToriJ25** [comment]
> Looks good - nice research on the details

Thank you!
