### ISSUE TITLE
Investigate AU_ACN Match

### ISSUE THREAD

**Issue by AmariBull** [NCATComp410/comp410_fall_2024#72]
# AU_ACN
ID:5

The output of the ACN does not look like it was correctly detected, too many numbers were entered.

**Comment by claesmk** [comment]
Do you think the number was not detected was not a valid AU_ACN?

**Comment by NiyaHen7** [comment]
It seems the number was detected but incorrectly classified as a DATE_TIME value. This could definitely be due to too many entered digits or the presence of letters in the input.

**Comment by claesmk** [comment]
The number is actually not a valid AU_ACN so it makes sense that it was not detected as such.

ID:5:Anonymized: The customer provided 2 ACN numbers.  The first number, <DATE_TIME>, is invalid.  The second number, <AU_ACN>, was correct

The fact that it was detected as a DATE_TIME was just random luck
