### ISSUE TITLE
PII Leak: CRYPTO

### ISSUE THREAD

**Issue by siblount** [NCATComp410/comp410_fall_2024#74]
After analyzing the test results, we found that for `ID: 13` did not fully anonymize the CRYPTO values.

```
ID:13:Original  : The customer's crypto wallet was incorrect - [REDACTED]- this was updated to [REDACTED]
ID:13:Anonymized: The customer's crypto wallet was incorrect - [REDACTED] - this was updated to <CRYPTO>
```

**Note:** The real values were replaced with `[REDACTED]` by me. `<CRYPTO>` is what the Presidio engine correctly identified and annonymized. 

As you can see, the crypto number after "The customer's crypto wallet was incorrect" was leaked but the updated value was not leaked.

**Comment by claesmk** [comment]
Great use of [REDACTED] to protect PII in the issue.  It's possible the [REDACTED] crytpo number is invalid.  What do you think?

**Comment by siblount** [comment]
You brought up a good point, it looks like a legitimate address at first glance but upon further deeper inspection, the supposedly leaked crypto PII is an invalid crypto number.
