### ISSUE TITLE
Detect AU_TFN

### ISSUE THREAD

**Issue by mlskinner** [NCATComp410/comp410_fall_2024#8]
### Description 
TFN stands for tax file number. Every taxpaying individual has one issued by the Austrailian Taxation Office. For more information, see [here](https://www.ato.gov.au/individuals-and-families/tax-file-number/what-is-a-tax-file-number).

### Description Steps 
AU_TFN is a unique sequence of digits in the format of 000 000 000

**Comment by NiyaHen7** [comment]
Does the digit structure of an AU_TFN carry any significance, such as encoding regional information or being based on the taxpayer's location or demographic details?

**Comment by mlskinner** [comment]
> Does the digit structure of an AU_TFN carry any significance, such as encoding regional information or being based on the taxpayer's location or demographic details?

It doesn't hold any significance. There is no embedded regional information and the number is generated randomly.

**Comment by bbyrd2021** [comment]
Is there a specific algorithm to use in order to detect a TFN?

**Comment by claesmk** [comment]
Looks good - What context words would help differentiate a TFN from other 9-digit numbers?

**Comment by mlskinner** [comment]
> Is there a specific algorithm to use in order to detect a TFN?

Each number of the TFN can be multiplied by a specific weight then added together, and if the result is a whole number then the TFN is varified.

**Comment by mlskinner** [comment]
> Looks good - What context words would help differentiate a TFN from other 9-digit numbers?

Tax return, payroll, TFN declaration statement, tax file number, and Austrailian Tax Office are all a few context words to help seperate itself from other 9-digit numbers
