### ISSUE TITLE
Investigate IT_DRIVER_LICENSE match

### ISSUE THREAD

**Issue by mawdogbe** [NCATComp410/comp410_fall_2024#82]
# IT_DRIVER_LICENSE
ID:41

It looks like a driver's license may not be correctly detected.

**Comment by mawdogbe** [comment]
This is actually not the case. Driver's Licenses are being detected properly and correctly anonymized.

**Comment by claesmk** [comment]
@mawdogbe can you provide some additional justification for why you believe this is true?

**Comment by mawdogbe** [comment]
@claesmk sure! When the scan code is ran, both "Italian" as well as the respective Italian driver's license are anonymized to prevent detection.
