### ISSUE TITLE
Investigate AU_ABN match

### ISSUE THREAD

**Issue by anrichardson1** [NCATComp410/comp410_fall_2024#85]
#AU_ABN
ID:3

It looks as if the user did not enter in an Australian Business Number but a US Bank Number which is too long and doesn't match the pattern for an AU ABN.

**Comment by claesmk** [comment]
@anrichardson1 it looks like you have exposed some PII in your comment by listing a valid AU ABN number

**Comment by anrichardson1** [comment]
Redo:

The replacement for the AU ABN was a valid and accurate replacement.

**Comment by anrichardson1** [comment]
> @anrichardson1 it looks like you have exposed some PII in your comment by listing a valid AU ABN number

Just replaced with a new statement to not leak the PII
