### ISSUE TITLE
Investigate IT_IDENTITY_CARD match

### ISSUE THREAD

**Issue by ComicalTNM** [NCATComp410/comp410_fall_2024#89]
# IT_IDENTITY_CARD
ID:45

It looks like an ID card might not be correctly detected.

**Comment by ComicalTNM** [comment]
The ID Card is anonymized as expected with <IT_IDENTITY_CARD>.

**Comment by claesmk** [comment]
Agree however this is a duplicate of #88 and this analysis is correct
