### ISSUE TITLE
Investigate Issues with PII Anonymization Detection

### ISSUE THREAD

**Issue by KennyH1886** [NCATComp410/comp410_fall_2024#93]
### Observations:
1. **Valid PII Not Fully Anonymized**:
   - **Example**: 
     - Input: `The customer's ssn was updated from 123-45-6789 to 078-05-1123.`
     - Output: `The customer's ssn was updated from <US_SSN> to 078-05-1123.`
   - **Issue**: The second SSN remains unmasked, which represents a PII leak.
   - **Impact**: This could lead to security vulnerabilities if the unmasked PII data is exposed.

2. **Potential False Positives**:
   - **Example**:
     - Input: `My favorite number is 12345.`
     - Output: `My favorite number is <US_SSN>.`
   - **Issue**: Non-PII numeric data was falsely identified as PII (SSN) and anonymized.
   - **Impact**: This could lead to data integrity issues when non-sensitive data is incorrectly anonymized.

### Suggestions for Improvement:
1. **Leveraging Recognition Scores**:
   - Use recognition scores to set dynamic thresholds for detecting valid PII entities. For example:
     - Lower thresholds for entities like SSNs and credit card numbers, which are more predictable.
     - Higher thresholds for ambiguous entities to avoid false positives.

2. **Implementing Context-Based Validation**:
   - Use contextual clues to improve detection accuracy. For instance, numeric strings following phrases like "SSN" or "social security" are more likely to be sensitive than random numeric strings.

3. **Post-Detection Validation**:
   - Add a validation step to ensure no valid PII entities are left unanonymized, especially when multiple instances occur in a single text.

### Next Steps:
- Discuss possible changes to the `analyze_text` function to address these issues.
- Explore extending the unit tests to cover edge cases such as those listed above.
- Investigate the feasibility of implementing changes based on Presidio documentation and anonymizer settings.

**Tags**:
- Team Name: Tech Bros
- Milestone: Sprint-3
- Labels: `pii leak`, `false positive`, `team discussion`

**Comment by KennyH1886** [comment]
Upon further analysis and validation of the VAT code anonymization functionality, it has been confirmed that the Presidio Anonymizer is correctly handling VAT codes as expected.

Resolution:
The test cases for IT_VAT_CODE, including both with and without context, passed successfully without any observed PII leaks or false positives.
Valid VAT codes are anonymized accurately, and invalid VAT codes are correctly ignored, ensuring compliance with expected functionality.
No further action is required for VAT code handling at this time.

**Comment by claesmk** [comment]
Your observations make sense, however, you exposed some potential PII in your issue description.  We all agree that 123-45-6789 is not valid and is not PII, however, the other number could be PII
